#服务提供方

server:
  port:  8888

spring:
  datasource:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/dubbo
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000
      database: 0
      jedis:
        pool:
         max-active: 10
         max-idle: 8
         min-idle: 2
         max-wait: 100

  dubbo:
    application:
      name: dubbo-provider
    base-package: com.sky.blog.provider    # dubbo服务发布者所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      port: 20880
    provider:
      retries: 0

  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sky.blog.provider.model






